# Generated by Django 4.2.10 on 2024-03-13 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0004_habit_notification_time_habit_telegram_chat_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habit',
            name='telegram_chat_id',
        ),
        migrations.AlterField(
            model_name='habit',
            name='periodicity',
            field=models.PositiveSmallIntegerField(blank=True, default=1, null=True, verbose_name='Периодичность'),
        ),
    ]
